### ISSUE TITLE
Link en pagina apunta a sitio protegido [BUG]

### ISSUE THREAD

**Issue by claudiods** [somos-criptonautas/trading#39]
## Description of the bug
Hay un link en una de las paginas del libro que apunta a un sitio protegido. Asumiendo que el capitulo es open source y para el publico en general esto no es correcto. Debiera sacarse el link o dejar publico el mismo.

## How to reproduce
Ir a https://trading.criptonautas.co/trading/vivir-del-trading/por-que-acumulo-btc-y-xmr/ y presionar el link que se encuentra en el segundo parrafo, donde dice "[su tendencia a largo plazo es alcista desde su creación](https://foro.btcarg.com.ar/t/analisis-btc-en-diciembre-2019-velas-semanales/185)"
Al hacer click, se llega a este otro sitio (a pesar de estar logueado como padawans): https://comunidad.criptonautas.co/t/importante-categorias-de-usuarios-en-criptonautas/64

**Expected behavior**
Que muestre el contenido del link.

## Screenshots
n/a

## Additional context
n/a

## Technical data
n/a

### Desktop (please complete the following information)
Desde Windows 11

### Smartphone (please complete the following information)
No testeado

**Comment by claudiods** [comment]
fue comentado en el mismo capitulo a pedido de Matias.

**Comment by satoshinotdead** [comment]
Hola Claudio, quitaste el link y enviaste el PR?

Los accesos están OK, y en caso de que no, serán revisados en otro momento. Por ahora nos enfocamos en los espacios a los cuales tenemos acceso porque afortunadamente hay mucho por hacer y aprender en ellos.

Abrazo.

**Comment by claudiods** [comment]
Quitaré el link porque así como está no le sirve a los lectores.

Y con respecto a los accesos, respeto eso. Claro, *me estoy enfocando en
aprender mucho*, pero fuera del foro criptonautas, ya que cada 5 clicks, 4
me banean y es muy frustrante trabajarlo de ese modo. Cuando se arregle
seguiré mi aprendizaje desde adentro y aportando como lo vengo haciendo en
Discord.

Un saludo,

*Claudio *
